title: ISMAUK Stress Management Awards 2026
description: Online application portal for the ISMAUK Stress Management Awards
theme: null
plugins: []

# GitHub Pages settings
markdown: GFM
highlighter: rouge
lsi: false
safe: true
incremental: false
gfm_quirks: paragraph_end

# Build settings
exclude:
  - .gitignore
  - README.md
  - LICENSE

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
